### ISSUE TITLE
unable to create signature without namespace prefix

### ISSUE THREAD

**Issue by wissamdagher** [MrMarchello/php-XmlDigitalSignature#1]
By default, all nodes in the generated XML document have a namespace prefix of dsig:. If you would like to specify a different ns prefix (or you don't want to use one at all), simply pass the appropriate value to the XmlDsig\XmlDigitalSignature::setNodeNsPrefix() method.

$dsig
		->setCryptoAlgorithm(XmlDsig\XmlDigitalSignature::RSA_ALGORITHM)
		->setDigestMethod(XmlDsig\XmlDigitalSignature::DIGEST_SHA256)
		->setCanonicalMethod(XmlDsig\XmlDigitalSignature::C14N_EXCLUSIVE)
		->setNodeNsPrefix('')
		->forceStandalone();

Prefix could not be empty

**Comment by MrMarchello** [comment]
Hi, thanks for posting this issue. It has been fixed in commit 4f23bd4c90.
