### ISSUE TITLE
Append signature to file

### ISSUE THREAD

**Issue by RonnieVisser** [MrMarchello/php-XmlDigitalSignature#2]
Does this library includes to append the signature to the original file? Of not, is there an easy way to do this?

**Comment by MrMarchello** [comment]
A signature is generated and appended to a newly formed, canonicalized XML document. Depending on the type of signature you are after, this may or may not be enough for you. Please provide more information about the signature spec you are after, maybe I can help with the implementation.

As far as being easy - from experience I can say that this usually isn't easy in PHP, but I should be able to guide you in the right direction.

**Comment by RonnieVisser** [comment]
Hi,




Thanks for your response. I have already fixed is so this can be closed.




Regards,

Ronnie



—
Verzonden via Mailbox
